spring.application.name=userAccount_springboot
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringAccount
spring.datasource.username=postgres
spring.datasource.password=4WogrX66

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkey

server.port=9191

